###############################################################################
# Jekyll Configuration
highlighter: rouge
markdown: kramdown
permalink: /:title.html
#paginate: 5
port: 3000
safe: true
language: 'en-uk'
plugins: [jekyll-feed]

###############################################################################
# Page Personal Details
url: http://naantunes.github.io/
baseurl: /
author: Nathália Antunes
title: Nathália Antunes
description: Personal Landing Page
avatar: nathalia.jpg

# Contacts
email: nathalia.antunes01@gmail.com

# Upon Request for Phone, Skype, Hangouts, etc.
urequest: Upon request

# Social Usernames for Twitter, Github, Medium, Linkedin
username: naantunes
